version: '3.8'
services:
  frontend:
    image: devops-project-main-frontend:latest
    ports:
      - "3000:80"
    deploy:
      replicas: 1

  backend:
    image: devops-project-main-backend:latest
    ports:
      - "5000:80"
    deploy:
      replicas: 1

  worker:
    image: devops-project-main-worker:latest
    environment:
      - REDIS_HOST=redis
      - SERVER_NAME=localhost
      - FLASK_ENV=development
    deploy:
      replicas: 1

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    deploy:
      replicas: 1